[phases.setup]
nixPkgs = ['...', 'nodejs_20']

[phases.install]
cmds = ['npm i -g pnpm && pnpm install']

[phases.build]
cmds = ['npx prisma generate --schema=packages/database/prisma/schema.prisma && cd apps/backend && pnpm build']

[start]
cmd = 'cd apps/backend && node dist/main'
