[phases.setup]
nixPkgs = ['...', 'nodejs_20']

[phases.install]
cmds = ['npm i -g pnpm && pnpm install']

[phases.build]
cmds = ['cd apps/backend && pnpm build']

[start]
cmd = 'cd apps/backend && node dist/main'
